services:
  backend:
    build:
      context: ./backend
    container_name: devops-backend
    environment:
      - SERVER_PORT=8080
      - APP_JWT_SECRET=${APP_JWT_SECRET}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
