---------------------------------------------------------
-- DROP TABLE (เพื่อความแน่นอนทุกครั้งที่รัน test)
---------------------------------------------------------
DROP TABLE IF EXISTS reservation_tickets CASCADE;
DROP TABLE IF EXISTS reserved_seats CASCADE;
DROP TABLE IF EXISTS reserved CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS seat_rows CASCADE;
DROP TABLE IF EXISTS seat_zones CASCADE;
DROP TABLE IF EXISTS seat_locks CASCADE;
DROP TABLE IF EXISTS ticket_types CASCADE;
DROP TABLE IF EXISTS events_nam CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS zone_ticket_types CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;

---------------------------------------------------------
--  TABLES (H2 PostgreSQL compatible)
---------------------------------------------------------

-- ============================
-- seat_zones
-- ============================
CREATE TABLE seat_zones (
                            zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            event_id BIGINT,
                            zone_name VARCHAR(255),
                            zone_code VARCHAR(255),
                            description VARCHAR(255),
                            sort_order INT,
                            row_start INT,
                            row_end INT,
                            price DECIMAL(19,2),
                            is_active BOOLEAN,
                            created_at TIMESTAMP,
                            updated_at TIMESTAMP
);

-- ============================
-- seat_rows
-- ============================
CREATE TABLE seat_rows (
                           row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           zone_id BIGINT,
                           row_label VARCHAR(50),
                           sort_order INT,
                           is_active BOOLEAN,
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP,
                           FOREIGN KEY (zone_id) REFERENCES seat_zones(zone_id)
);

-- ============================
-- seats
-- ============================
CREATE TABLE seats (
                       seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       row_id BIGINT NOT NULL,
                       seat_number INT NOT NULL,
                       seat_label VARCHAR(100),
                       is_active BOOLEAN,
                       created_at TIMESTAMP,
                       updated_at TIMESTAMP,
                       FOREIGN KEY (row_id) REFERENCES seat_rows(row_id)
);

-- ============================
-- reserved
-- ============================
CREATE TABLE reserved (
                          reserved_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT,
                          event_id BIGINT,
                          ticket_type_id BIGINT,
                          quantity INT,
                          total_amount DECIMAL(10,2),
                          payment_status VARCHAR(50),
                          registration_datetime TIMESTAMP,
                          payment_datetime TIMESTAMP,
                          confirmation_code VARCHAR(100),
                          notes VARCHAR(255),
                          payment_method VARCHAR(50),
                          guest_email VARCHAR(255),
                          guest_claimed_at TIMESTAMP,
                          created_as_guest BOOLEAN
);

-- ============================
-- reserved_seats
-- ============================
CREATE TABLE reserved_seats (
                                reserved_seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                reserved_id BIGINT NOT NULL,
                                seat_id BIGINT NOT NULL,
                                seat_status VARCHAR(50),
                                FOREIGN KEY (reserved_id) REFERENCES reserved(reserved_id),
                                FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
);

-- ============================
-- seat_locks
-- ============================
CREATE TABLE seat_locks (
                            lock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            seat_id BIGINT,
                            event_id BIGINT,
                            user_id BIGINT,
                            started_at TIMESTAMP,
                            expires_at TIMESTAMP,
                            status VARCHAR(50),
                            FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
);

-- ============================
-- ticket_types
-- ============================
CREATE TABLE ticket_types (
                              ticket_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              event_id BIGINT,
                              type_name VARCHAR(255),
                              description VARCHAR(500),
                              price DECIMAL(19,2),
                              quantity_available INT,
                              quantity_sold INT,
                              sale_start_datetime TIMESTAMP,
                              sale_end_datetime TIMESTAMP,
                              is_active BOOLEAN,
                              min_per_order INT,
                              max_per_order INT,
                              created_at TIMESTAMP,
                              updated_at TIMESTAMP
);

-- ============================
-- zone_ticket_types
-- ============================
CREATE TABLE zone_ticket_types (
                                   zone_id BIGINT NOT NULL,
                                   ticket_type_id BIGINT NOT NULL,
                                   PRIMARY KEY (zone_id, ticket_type_id),
                                   FOREIGN KEY (zone_id) REFERENCES seat_zones(zone_id),
                                   FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(ticket_type_id)
);

-- ============================
-- reservation_tickets
-- ============================
CREATE TABLE reservation_tickets (
                                     reservation_id BIGINT,
                                     ticket_type_id BIGINT,
                                     seat_row VARCHAR(50),
                                     seat_col VARCHAR(50),
                                     price DECIMAL(10,2)
);

-- ============================
-- events_nam
-- ============================
CREATE TABLE events_nam (
                            event_id BIGINT PRIMARY KEY,
                            event_name VARCHAR(255),
                            venue_name VARCHAR(255),
                            start_datetime TIMESTAMP,
                            sales_end_datetime TIMESTAMP
);

-- ============================
-- users
-- ============================
CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) UNIQUE NOT NULL,
                       email VARCHAR(150) UNIQUE NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       roles VARCHAR(50) NOT NULL,
                       first_name VARCHAR(100),
                       last_name VARCHAR(100),
                       phone_number VARCHAR(30),
                       id_card_passport VARCHAR(30)
);

-- ============================
-- user_sessions
-- ============================
CREATE TABLE user_sessions (
                               session_id VARCHAR(255) PRIMARY KEY,
                               user_id BIGINT,
                               created_at TIMESTAMP,
                               expires_at TIMESTAMP,
                               is_active BOOLEAN,
                               last_activity TIMESTAMP,
                               ip_address VARCHAR(255),
                               user_agent VARCHAR(500)
);

---------------------------------------------------------
-- INDEXES (Performance)
---------------------------------------------------------
CREATE INDEX idx_seat_zones_event_id ON seat_zones(event_id);
CREATE INDEX idx_seat_zones_sort_order ON seat_zones(sort_order);
CREATE INDEX idx_seat_rows_zone_id ON seat_rows(zone_id);
CREATE INDEX idx_seats_row_id ON seats(row_id);
CREATE INDEX idx_reserved_seats_reserved_id ON reserved_seats(reserved_id);
CREATE INDEX idx_reserved_seats_seat_id ON reserved_seats(seat_id);
CREATE INDEX idx_seat_locks_seat_id ON seat_locks(seat_id);
CREATE INDEX idx_seat_locks_event_id ON seat_locks(event_id);
CREATE INDEX idx_seat_locks_user_id ON seat_locks(user_id);
CREATE INDEX idx_ticket_types_event_id ON ticket_types(event_id);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_zone_ticket_types_zone_id ON zone_ticket_types(zone_id);
CREATE INDEX idx_zone_ticket_types_ticket_type_id ON zone_ticket_types(ticket_type_id);
CREATE INDEX idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX idx_user_sessions_expires_at ON user_sessions(expires_at);
