DROP TABLE IF EXISTS seat_locks;

CREATE TABLE seat_locks (
                            lock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            seat_id BIGINT,
                            event_id BIGINT,
                            user_id BIGINT,
                            started_at TIMESTAMP,
                            expires_at TIMESTAMP,
                            status VARCHAR(50)
);
