DROP TABLE IF EXISTS reserved_seats CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS seat_rows CASCADE;
DROP TABLE IF EXISTS seat_zones CASCADE;

CREATE TABLE seat_zones (
                            zone_id BIGINT PRIMARY KEY,
                            event_id BIGINT,
                            zone_name VARCHAR(100)
);

CREATE TABLE seat_rows (
                           row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           zone_id BIGINT NOT NULL,
                           row_label VARCHAR(20),
                           sort_order INT,
                           is_active BOOLEAN,
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP
);
