---------------------------------------------------------
--  ของเดิมของน้อง (เก็บไว้ทั้งหมด)
---------------------------------------------------------
CREATE TABLE seat_zones (
                            zone_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            event_id BIGINT
);

CREATE TABLE seat_rows (
                           row_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                           zone_id BIGINT,
                           row_label VARCHAR(50),
                           sort_order INT,
                           is_active BOOLEAN,
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP
);


---------------------------------------------------------
--  ของเดิมที่น้องให้มา (ไม่ตัดออก)
---------------------------------------------------------
CREATE TABLE seats (
                       seat_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                       row_id BIGINT NOT NULL,
                       seat_number INT NOT NULL,
                       seat_label VARCHAR(100),
                       is_active BOOLEAN,
                       created_at TIMESTAMP,
                       updated_at TIMESTAMP,
                       FOREIGN KEY (row_id) REFERENCES seat_rows(row_id)
);

CREATE TABLE reserved (
                          reserved_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          event_id BIGINT,
                          ticket_type_id BIGINT,
                          payment_status VARCHAR(50)
);

CREATE TABLE reserved_seats (
                                reserved_seat_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                reserved_id BIGINT NOT NULL,
                                seat_id BIGINT NOT NULL,
                                seat_status VARCHAR(50),
                                FOREIGN KEY (reserved_id) REFERENCES reserved(reserved_id),
                                FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
);

CREATE TABLE seat_locks (
                            lock_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            seat_id BIGINT,
                            event_id BIGINT,
                            user_id BIGINT,
                            started_at TIMESTAMP,
                            expires_at TIMESTAMP,
                            status VARCHAR(50),
                            FOREIGN KEY (seat_id) REFERENCES seats(seat_id)
);

CREATE TABLE ticket_types (
                              ticket_type_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                              event_id BIGINT,
                              name VARCHAR(100),
                              price DECIMAL(10,2)
);

-- H2 ไม่มี VIEW → Mock table
CREATE TABLE reservation_tickets (
                                     reservation_id BIGINT,
                                     ticket_type_id BIGINT,
                                     seat_row VARCHAR(50),
                                     seat_col VARCHAR(50)
);


---------------------------------------------------------
-- ⭐⭐ ส่วนที่พี่ “เพิ่ม” ให้ H2 ใช้จริง (ไม่ลบของเดิม)
--     ใช้ GENERATED AS IDENTITY (รองรับ H2 2.x)
---------------------------------------------------------

CREATE TABLE seat_zones_fix (
                                zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                event_id BIGINT
);

CREATE TABLE seat_rows_fix (
                               row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               zone_id BIGINT,
                               row_label VARCHAR(50),
                               sort_order INT,
                               is_active BOOLEAN,
                               created_at TIMESTAMP,
                               updated_at TIMESTAMP
);

CREATE TABLE seats_fix (
                           seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           row_id BIGINT NOT NULL,
                           seat_number INT NOT NULL,
                           seat_label VARCHAR(100),
                           is_active BOOLEAN,
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP
);

CREATE TABLE reserved_fix (
                              reserved_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              event_id BIGINT,
                              ticket_type_id BIGINT,
                              payment_status VARCHAR(50)
);

CREATE TABLE reserved_seats_fix (
                                    reserved_seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    reserved_id BIGINT NOT NULL,
                                    seat_id BIGINT NOT NULL,
                                    seat_status VARCHAR(50)
);

CREATE TABLE seat_locks_fix (
                                lock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                seat_id BIGINT,
                                event_id BIGINT,
                                user_id BIGINT,
                                started_at TIMESTAMP,
                                expires_at TIMESTAMP,
                                status VARCHAR(50)
);

CREATE TABLE ticket_types_fix (
                                  ticket_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  event_id BIGINT,
                                  name VARCHAR(100),
                                  price DECIMAL(10,2)
);

CREATE TABLE reservation_tickets_fix (
                                         reservation_id BIGINT,
                                         ticket_type_id BIGINT,
                                         seat_row VARCHAR(50),
                                         seat_col VARCHAR(50)
);
